### ISSUE TITLE
after migrating to 6 I can't build

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#425]
## Please, provide the details below:
I've followed the upgrade instructions here: 
### Did you verify whether this issue has already been reported here?
Yes - looks like similar webpack problems are reported, but mine is exit code 1 not 2

### Tell us about the problem
when running nativescript sidekick build
Error: Cannot find module '/Users/brice/source/repos/classappnativescript/node_modules/webpack/bin/webpack.js'

### Which platform(s) does the issue occur on?
both ios and android on mac

### Provide the following version numbers that the issue occurs with:

Version: 1.19.1-v.2019.8.1.2 (latest)
NativeScript CLI version: 6.1.2
CLI extension nativescript-cloud version: 1.18.2
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start nativescript sidekick
2. .open a virtual device
3. Run on Device

### Does this issue happen every time?
yes

### Send the client logs
[main_19-09-23_15-11-42.197.log](https://github.com/NativeScript/sidekick-feedback/files/3643756/main_19-09-23_15-11-42.197.log)
[console_19-09-23_15-11-38.990.log](https://github.com/NativeScript/sidekick-feedback/files/3643757/console_19-09-23_15-11-38.990.log)

**Comment by bradrice** [comment]
I discovered I had to npm i webpack for some reason after I upgraded. It is running now.
